### ISSUE TITLE
moduly

### ISSUE THREAD

**Issue by lsiedlaczek** [konradkukier2/Image-Processing#1]
wszystkie funkcje przypiete sa do window. robisz przez to global pollution.
uzywaj prosze namespaceow / modulow (skorzystaj z revealing module pattern).

**Comment by konradkukier2** [comment]
fixed

**Comment by lsiedlaczek** [comment]
stworzyles jeden modul.

jak dla mnie to tu powinny byc co najmniej 3 moduly:
. drag&drop
. canvas (tworzenie miniatur, etc.)
. fileUpload (wrzucanie pliku i odpalenie jego przetwarzania)

kazdy modul powinien byc wlasciwie od siebie niezalezny. powinien spinac je jeden kontroler.
