### ISSUE TITLE
miniatury

### ISSUE THREAD

**Issue by lsiedlaczek** [konradkukier2/Image-Processing#2]
miniatury powinny byc tworzone na canvasie. to ze ustawisz width = 150 nie oznacza ze obrazek sie zmniejszy. zmniejszy sie jedynie wielkosc wyswietlanego przez niego obiektu. on w pamieci wciaz bedzie wazyl tyle co wgrany obrazek

**Comment by konradkukier2** [comment]
Fixed. Poprawnie jest teraz?

**Comment by lsiedlaczek** [comment]
nie. powinienes dopasowywac miniatury a nie ciac na pale.

**Comment by konradkukier2** [comment]
Masz na mysli ta konfigurowalnosc, zeby pozbyc sie magic number (w postaci aktualnej 150) czy cos innego? Bo jak cos innego to nie rozumiem nadal.

**Comment by lsiedlaczek** [comment]
troche tak, ale sprobuj bedzie latwiej nam dyskutowac na gotowych rozwiazaniach :)
