### ISSUE TITLE
konfigurowalnosc

### ISSUE THREAD

**Issue by lsiedlaczek** [konradkukier2/Image-Processing#3]
powinienes miec mozliwosc konfiguracji na jakich obiektach chcesz operowac, a nie miec na sztywno przypiete np. #browserInput
magiczne liczby (width / height) tez powinny byc konfigurowalne.

co jesli przeniesiesz ten modul do nowej aplikacji. bedzie dzialac out of a box?

**Comment by konradkukier2** [comment]
Na chwile obecna nie wiem od czego zaczac, jakas podpowiedz?

**Comment by lsiedlaczek** [comment]
http://filepi.com/i/g8eOaFF - poszukaj czesci o config pattern + zastanow sie jak ustawic defaultsy
