### ISSUE TITLE
replaceChild

### ISSUE THREAD

**Issue by lsiedlaczek** [konradkukier2/Image-Processing#7]
dlaczego uzywasz tej funkcji?

**Comment by konradkukier2** [comment]
bo wrzucam na strone img, ktory ma onload przypisanego canvasa, wiec jak sie odpali funkcja i appenduje canvasa, to musze sie pozbyc tego img, wpadlem na replace. Nie mam poki co pomyslu jak to obejsc bo jak robie canvas na img, ktory sie nie zaladowal to nie bangla.

**Comment by lsiedlaczek** [comment]
wiec poczekaj na wykonanie onload i wtedy na nim operuj :)
21 lip 2015 21:57 "konradkukier2" <notifications@github.com> napisał(a):

**Comment by konradkukier2** [comment]
done
