### ISSUE TITLE
conf

### ISSUE THREAD

**Issue by lsiedlaczek** [konradkukier2/Image-Processing#8]
conf nie powinien byc w osobnym pliku i nie powinien byc zmienna globalna.
powinien byc przekazywany jako parametr do modulow, zeby robily sobie z tego wartosc lokalna.

**Comment by konradkukier2** [comment]
Dobra, poddaje sie, nie umiem, nie ogarniam, nie rozumiem, siedzialem pol dnia i nie wiem jak to zrobic, domyslam sie, ze mam pewnie wywolac anonimowa funkcje ktora zadeklaruje obiekt conf i przekaze go dalej jako argument, ale do czego? jak do modulow? Nie mam pojecia i szczerze to nie mam juz sily do tego.

**Comment by lsiedlaczek** [comment]
Konrad, nie irytuj sie, idzie Ci dobrze.
zrob sobie dzien przerwy jesli potrzebujesz odswiezenia umyslu.

ponizej przyklad jak ja bym to zrobil na szybko

var someModule = (function() {
  var defaults = { ... }; // ustawiasz defaulty
  
  function init(config) {
    config = extend(defaults, config);
    // inicjalizacja modulu
    
    return {
      someFn: someFn,
      someFn2: someFn2
    }

    function extend(object1, object2) {
      // funkcja rozszerzajaca obiekt1 o obiekt2
    }

    function someFn() { ... }

    function someFn2(params) { ... }
  } 

  return {
    init: init
  } 
  // mozesz tez po prostu zrobic: return init jesli nie bedziesz mial innych elementow w tym obiekcie 
  // usage 2
})();

var someModuleInstance = someModule.init({ width: 100, height: 200 });

usage 2:
var someModuleInstance = someModule({ width: 100, height: 200 });
et voila!

**Comment by konradkukier2** [comment]
Jakbys mial chwile, moglbys to w skrocie (moze byc bez extend itp bo jakby sam kod rozumiem) napisac na przykladzie mojego kodu? Wydaje mi sie, ze moim problemem jest tutaj jakby implementacja rozwiazania. Nie wiem czy moj skrypt jest tak bardzo niedostosowany, ze to ciezko zrobic, czy po prostu nie widze sensownej drogi jak to zrobic.

Probowalem na koniec control.js wrapnac funkcje

(function () { 
   var conf = { tWidth: 150, tHeight: 150 };

   controlModule.start(conf);
})();

ale potem musialbym argument conf co chwila gdzies wpychac i mi sie to wszystko rozjezdza - chyba zly approach.

Teoretyczny przyklad jaki mi dales, na ta chwile mi nic nie rozjasnil niestety.

**Comment by lsiedlaczek** [comment]
spoko. tylko ze za 30min wsiadam do pociagu. dojezdzam o 23.00 wiec jesli
bede jeszcze na chodzie to to ogarne. jesli nie to jutro rano.

**Comment by lsiedlaczek** [comment]
ok, a wiec: 
moduly traktuj jak serwisy, czy zewnetrzne biblioteki. 
Twoj controlModule, de facto jest kontrolerem, czyli czyms bardzo specyficznym dla danej aplikacji, nie ubieraj go wiec w modul a po prostu wywolaj w ramach strony, spiete w iife.

dalej:
listenery + drophandler wyrzuc do d&d, te doPrevent, doStopProp sa zbyt szczegolowe, wiec je wyrzuc w ogole.
ten browse tez dla mnie jest do wyrzucenia.

lepiej w samym kontrolerze zrobic:
```javascript
// tutaj konfigurujesz sobie rzeczy z imageProca, 
// tak zeby mial juz ustawione odpowiednie defaultsy, etc.
var gallery = imageProc.start({
  width: 10,
  height: 100,
  etc.
});

dragDrop.start({
  buttonId: '#something',
  // ustawiasz callbacka, ktorego bedziesz wywolywac w d&d
  // dzieki temu d&d nie jest zalezny od jakiegokolwiek modulu a jedynie od tego bys w konfigu
  // podal mu funkcje na jakiej ma dzialac
  callback: gallery.doProc 
)
```

**Comment by konradkukier2** [comment]
Dobra to call bo nie rozumiem. Kiedy? Jak dla mnie to asap bo nic mnie tak dawno nie wkurwialo, spac przez to nie moge, daj znac kiedy najwczesniej Ci pasuje.

**Comment by konradkukier2** [comment]
Sprawdzisz teraz? Z rana podjalem kolejna probe i wrzucilem juz jej efekt na githuba.

**Comment by lsiedlaczek** [comment]
zadzwon do mnie albo wyslij mi swoj nr na maila

**Comment by konradkukier2** [comment]
Kolejna proba uploaded.

**Comment by lsiedlaczek** [comment]
ok, pytanie tylko: dlaczego imgProcModule zwraca funkcje a pozostale zwracaja obiekt z pojedyncza metoda start?

+ wdroz w zycie pozostale uwagi

**Comment by konradkukier2** [comment]
No nie ma znaczenia, jak obiekt ma jeden element (metode) to moge w zasadzie po prostu ja zwrocic, nie? W reszcie nie przerabialem bo a) i tak mowiles, ze bedziemy orac przyklad b) nie wiedzialem, czy dojdzie mi jeszcze do zwracania cos.

**Comment by lsiedlaczek** [comment]
qok. to oraj i napisz to od nowa. tym razem z dobrym nazewnictwem ;)
19 lip 2015 15:35 "konradkukier2" <notifications@github.com> napisał(a):

**Comment by konradkukier2** [comment]
Tak samo, o ile dobrze rozumiem to moj imageProcFactory w zasadzie tez jeszcze powinienem w modul ubrac, nie?

**Comment by lsiedlaczek** [comment]
1. tak
2. nie wiem dlaczego nie robisz po prostu zwyklego appendChild

**Comment by konradkukier2** [comment]
Napisane od nowa.

Re 2 : bo wrzucam na strone img, ktory ma onload przypisanego canvasa, wiec jak sie odpali funkcja i appenduje canvasa, to musze sie pozbyc tego img, wpadlem na replace. Nie mam poki co pomyslu jak to obejsc bo jak robie canvas na img, ktory sie nie zaladowal to nie bangla.
